### ISSUE TITLE
[bug] terracognita 0.7.0 build failed on apple arm64

### ISSUE THREAD

**Issue by chenrui333** [cycloidio/terracognita#195]
**General information:**

* Operating System: macOS 11-arm64
* Terracognita version / tag: 0.7.4
* Did you build Terracognita from sources or did you use the Docker image: source code

**Describe the bug:**

terracognita 0.7.0 build failed on apple arm64

**Log message**

```
# github.com/cycloidio/terracognita
net(__TEXT/__text): program too large, call relocation distance = 148372148
net(__TEXT/__text): program too large, call relocation distance = 148372128
net(__TEXT/__text): program too large, call relocation distance = 148372108
net(__TEXT/__text): program too large, call relocation distance = 148372024
net(__TEXT/__text): program too large, call relocation distance = 148371940
net(__TEXT/__text): program too large, call relocation distance = 148371948
net(__TEXT/__text): program too large, call relocation distance = 148371916
net(__TEXT/__text): program too large, call relocation distance = 148371904
net(__TEXT/__text): program too large, call relocation distance = 148371880
net(__TEXT/__text): program too large, call relocation distance = 148371780
os/user(__TEXT/__text): program too large, call relocation distance = 148371748
os/user(__TEXT/__text): program too large, call relocation distance = 148371724
os/user(__TEXT/__text): program too large, call relocation distance = 148371700
os/user(__TEXT/__text): program too large, call relocation distance = 148371668
os/user(__TEXT/__text): program too large, call relocation distance = 148371600
os/user(__TEXT/__text): program too large, call relocation distance = 148371532
os/user(__TEXT/__text): program too large, call relocation distance = 148371464
os/user(__TEXT/__text): program too large, call relocation distance = 148371404
os/user(__TEXT/__text): program too large, call relocation distance = 148371344
runtime/cgo(__TEXT/__text): program too large, call relocation distance = 148371252
runtime/cgo(__TEXT/__text): program too large, call relocation distance = 148371256
/opt/homebrew/Cellar/go/1.16.5/libexec/pkg/tool/darwin_arm64/link: too many errors
unexpected fault address 0x2d230a750
fatal error: fault
unexpected fault address 0x2d2405b00
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x2d230a750 pc=0x10233e228]
```

**Additional context**

relates to:
- https://github.com/Homebrew/homebrew-core/pull/80450

**Comment by xescugc** [comment]
Looks related to https://github.com/golang/go/issues/40492 which is now solved but released within the `1.17`.

I would say that for now there is not much to do with it, having a big binary is something we know and I plan to try to work on, but there is not any easy solution for it AFAIK.

I would say to wait until `1.17` is released and try it with that version.

**Comment by chenrui333** [comment]
@xescugc I dont think it is related to that issue, because it was built out [fine this April 29](https://github.com/Homebrew/homebrew-core/pull/76271) with [go1.16.3](https://github.com/Homebrew/homebrew-core/blob/c4fc7758fdb1903b2fc5a60bbe815ed89cf1b880/Formula/go.rb)

Here is the build log.
https://github.com/Homebrew/homebrew-core/runs/2466540478

**Comment by chenrui333** [comment]
I am actually surprised that github action still does not support apple arm yet, which make things bad.

**Comment by xescugc** [comment]
IDK how to actually solve it, we know the size it has and it's hard to compile, we want to find a way to reduce it but it's not that easy.

IDK what can be the solution for this issue :(.

**Comment by chenrui333** [comment]
yeah, it is complicated. 🤦

**Comment by xescugc** [comment]
I was gonna mention that we released 0.7.1 but I see you already have a PR on it, just in case for that works, there is no change regarding sizes.
